services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortify
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: shortify
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/shortify?sslmode=disable
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/tmp

volumes:
  pgdata:
